### ISSUE TITLE
Promise improvement

### ISSUE THREAD

**Issue by acarnd03** [maven0571/ruhs-examples#2]
+ Thanks for examples 😀
+ In [ping-pong.js#L11](https://github.com/maven0571/ruhs-examples/blob/master/ping-pong.js#L11) and [caps-protection.js#L18](https://github.com/maven0571/ruhs-examples/blob/master/caps-protection.js#L18), `sendMessage` method is promise so you must use `await`.

**Comment by maven0571** [comment]
Fixed
